hostab-web/config/routes.rb
# -*- encoding : utf-8 -*-
HostabWeb::Application.routes.draw do
  apipie

  namespace :api do
    namespace :v1 do
      resources :delivery_locations
    	scope "/users/:user_id" do
    		resources :orders, only: [:create, :update, :show, :index]
    	end

      scope "/orders/:order_id" do
        resources :order_items, only: [:create, :index, :destroy, :show, :update]
      end

      resources :auth, only: [:create]
      resources :food_types, only: [:index] do
        resources :foods, only: [:index, :show]
      end
    end
  end
  namespace :kitchen do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'
    get   '/polling_orders', to: 'home#polling_orders'
    put '/set_as_ready/:order_id', to: 'home#set_as_ready', as: 'kitchen_ready'

    resources :home, only: [:index, :destroy]
  end
  
  namespace :admin do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'

    resources :home, only: [:index]
    resources :delivery_locations
    resources :menus
    resources :food_types do
      resources :foods
    end

    scope 'food/:id/' do
      post '/image',    to: 'foods#add_image'
      delete '/image/:image_id',  to: 'foods#remove_image', as: 'remove_image'
    end

    resources :promotions, only: [:index]
    resources :room_services, only: [:index]
    resources :users, only: [:edit, :update]

    get '/guests/search', to: 'guests#search'
    resources :guests

    root to: "home#index"
  end
  

  root to: "apipie/apipies#index"
end

hostab-web/app/controllers/admin/food_types_controller.rb
class Admin::FoodTypesController < AdminController

  def index
    @food_types = FoodType.unscoped.all
  end

  def new
    @food_type = FoodType.new
  end

  def create
    @food_type = current_user.company.food_types.create(params[:food_type])
    if @food_type.save
      redirect_to admin_menus_path
    else
      render :new
    end
  end

  def edit
    @food_type = FoodType.unscoped.find(params[:id])
  end

  def update
    @food_type = FoodType.unscoped.find(params[:id])
    @food_type.update_attributes(params[:food_type])
    if @food_type.save
      redirect_to admin_menus_path
    else
      render :edit
    end
  end

  def destroy
    FoodType.unscoped.destroy(params[:id])
    redirect_to admin_menus_path
  end
end

hostab-web/app/controllers/api/v1/food_types_controller.rb
# -*- encoding : utf-8 -*-
class Api::V1::FoodTypesController < ApiController

	api :GET, '/food_types/'
	description "Retorna as categorias existentes no cardápio"
	def index
		render json: FoodType.order(:position)
	end

end

hostab-web/app/views/admin/food_types/_form.html.erb
<%= form_for([:admin, @food_type], html: { :class => "form-horizontal well" }) do |f| %>
  <div class="control-group">
    <%= f.label :name, 'Nome', :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :locale, 'Idioma', :class => "control-label" %>
    <div class="controls">
      <%= f.select :locale, ['pt-BR', 'en'].map { |l| [l, l] }%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Salvar', :class => "btn btn-primary"%>
    <%= link_to 'Cancelar', admin_food_types_path, :class => "btn" %>
  </div>
<% end %>

hostab-web/app/views/admin/food_types/edit.html.erb
<div class="page-header">
  <h1>Editar categoria "<%= @food_type.name %>"</h1>
</div>
<%= render 'admin/food_types/form' %>

hostab-web/app/views/admin/food_types/index.html.erb
<div class="page-header">
  <h1>Categorias do cardápio</h1>
</div>
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th>Idioma</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @food_types.each do |ft| %>
      <tr>
        <td><%= ft.id %></td>
        <td><%= ft.name %></td>
        <td><%= ft.locale%></td>
        <td>
          <%= link_to 'Editar categoria', edit_admin_food_type_path(ft) %>
          <%= link_to 'Ver itens', admin_food_type_foods_path(ft)%>
          <%= link_to 'Remover Categoria', admin_food_type_path(ft), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Criar nova categoria', new_admin_food_type_path, :class => "btn btn-success" %>

hostab-web/app/views/admin/food_types/new.html.erb
<div class="page-header">
  <h1>Criar nova categoria do Cardápio</h1>
</div>

<%= render 'admin/food_types/form' %>