hostab-web/config/routes.rb
# -*- encoding : utf-8 -*-
HostabWeb::Application.routes.draw do
  apipie

  namespace :api do
    namespace :v1 do
      resources :delivery_locations
    	scope "/users/:user_id" do
    		resources :orders, only: [:create, :update, :show, :index]
    	end

      scope "/orders/:order_id" do
        resources :order_items, only: [:create, :index, :destroy, :show, :update]
      end

      resources :auth, only: [:create]
      resources :food_types, only: [:index] do
        resources :foods, only: [:index, :show]
      end
    end
  end
  namespace :kitchen do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'
    get   '/polling_orders', to: 'home#polling_orders'
    put '/set_as_ready/:order_id', to: 'home#set_as_ready', as: 'kitchen_ready'

    resources :home, only: [:index, :destroy]
  end
  
  namespace :admin do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'

    resources :home, only: [:index]
    resources :delivery_locations
    resources :menus
    resources :food_types do
      resources :foods
    end

    scope 'food/:id/' do
      post '/image',    to: 'foods#add_image'
      delete '/image/:image_id',  to: 'foods#remove_image', as: 'remove_image'
    end

    resources :promotions, only: [:index]
    resources :room_services, only: [:index]
    resources :users, only: [:edit, :update]

    get '/guests/search', to: 'guests#search'
    resources :guests

    root to: "home#index"
  end
  

  root to: "apipie/apipies#index"
end

hostab-web/app/models/delivery_location.rb
class DeliveryLocation < ActiveRecord::Base
   attr_accessible :name
   belongs_to :company
   has_many :orders

   validates :name, presence: true
end

hostab-web/app/controllers/admin/delivery_locations_controller.rb
class Admin::DeliveryLocationsController < AdminController
  def index
    @delivery_locations = DeliveryLocation.all
  end

  def new
    @delivery_location = DeliveryLocation.new
  end

  def create
    @delivery_location = current_user.company.delivery_locations.create(params[:delivery_location])
    if @delivery_location.save
      redirect_to admin_delivery_locations_path
    else
      render :new
    end
  end

  def edit
    @delivery_location = DeliveryLocation.find(params[:id])
  end

  def update
    @delivery_location = DeliveryLocation.find(params[:id])
    @delivery_location.update_attributes(params[:delivery_location])

    if @delivery_location.save
      redirect_to admin_delivery_locations_path
    else
      render :edit
    end
  end

  def destroy
    DeliveryLocation.destroy(params[:id])
    redirect_to admin_delivery_locations_path
  end
end

hostab-web/app/controllers/api/v1/delivery_locations_controller.rb
class Api::V1::DeliveryLocationsController < ApiController
  
  api :GET, "/delivery_locations"
  description "Retorna todos os destinos de entrega cadastradas para o hotel"
  def index
   render json: current_company.delivery_locations.all.to_json
  end
end

hostab-web/app/views/admin/delivery_locations/_form.html.erb
<%= form_for([:admin, @delivery_location], html: { :class => "form-horizontal well" }) do |f| %>
  <div class="control-group">
    <%= f.label :name, 'Nome', :class => "control-label" %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit 'Salvar', :class => "btn btn-primary"%>
    <%= link_to 'Cancelar', admin_delivery_locations_path, :class => "btn" %>
  </div>
<% end %>

hostab-web/app/views/admin/delivery_locations/edit.html.erb
<div class="page-header">
  <h1>Editar local <%= @delivery_location.name%></h1>
</div>

<%= render 'admin/delivery_locations/form' %>

hostab-web/app/views/admin/delivery_locations/index.html.erb
<div class="page-header">
  <h1>Locais de entrega</h1>
</div>
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Nome</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @delivery_locations.each do |d| %>
      <tr>
        <td><%= d.id %></td>
        <td><%= d.name %></td>
        <td>
          <%= link_to 'Editar local', edit_admin_delivery_location_path(d) %>
          <%= link_to 'Remover local', admin_delivery_location_path(d), method: :delete, confirm: 'Deseja realmente remover este local?' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Criar novo local', new_admin_delivery_location_path, :class => "btn btn-success" %>

hostab-web/app/views/admin/delivery_locations/new.html.erb
<div class="page-header">
  <h1>Criar novo Local</h1>
</div>

<%= render 'admin/delivery_locations/form' %>