hostab-web/config/routes.rb
# -*- encoding : utf-8 -*-
HostabWeb::Application.routes.draw do
  apipie

  namespace :api do
    namespace :v1 do
      resources :delivery_locations
    	scope "/users/:user_id" do
    		resources :orders, only: [:create, :update, :show, :index]
    	end

      scope "/orders/:order_id" do
        resources :order_items, only: [:create, :index, :destroy, :show, :update]
      end

      resources :auth, only: [:create]
      resources :food_types, only: [:index] do
        resources :foods, only: [:index, :show]
      end
    end
  end
  namespace :kitchen do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'
    get   '/polling_orders', to: 'home#polling_orders'
    put '/set_as_ready/:order_id', to: 'home#set_as_ready', as: 'kitchen_ready'

    resources :home, only: [:index, :destroy]
  end
  
  namespace :admin do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'

    resources :home, only: [:index]
    resources :delivery_locations
    resources :menus
    resources :food_types do
      resources :foods
    end

    scope 'food/:id/' do
      post '/image',    to: 'foods#add_image'
      delete '/image/:image_id',  to: 'foods#remove_image', as: 'remove_image'
    end

    resources :promotions, only: [:index]
    resources :room_services, only: [:index]
    resources :users, only: [:edit, :update]

    get '/guests/search', to: 'guests#search'
    resources :guests

    root to: "home#index"
  end
  

  root to: "apipie/apipies#index"
end

hostab-web/app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index
  	@orders = Order.unclosed.order('created_at DESC').limit(10)
  	@users = current_user.company.users.current_at_hotel
  end
end

hostab-web/app/controllers/kitchen/home_controller.rb
class Kitchen::HomeController < AdminController

  layout 'kitchen'
  def index
    @orders = current_user.company.orders.where('status != 2').order('created_at DESC')
  end

  def polling_orders
    @orders = current_user.company.orders.where('status != ? AND created_at > ?', 2, Time.at(params[:after].to_i + 1)).order('created_at DESC')
    render partial: 'list'
  end

  def set_as_ready
    @order = Order.find(params[:order_id])
    @order.set_status :delivered
    @order.save
    redirect_to kitchen_home_index_path
  end

  def destroy
    Order.destroy(params[:id])
    redirect_to kitchen_home_index_path
  end

end

hostab-web/app/controllers/kitchen/sessions_controller.rb
class Kitchen::SessionsController < ApplicationController
  skip_before_filter :restrict_access
  layout false

  def new
  end

  def create
    @user = Admin::User.authenticate(params[:email], params[:password])
    unless @user.nil?
      session[:admin_user_id] = @user.id
      redirect_to kitchen_home_index_path
    else
      flash[:notice] = 'Email ou Senha invalidos'
      redirect_to kitchen_sign_in_path 
    end
  end

  def destroy
    session[:admin_user_id] = nil
    redirect_to kitchen_sign_in_path
  end
end

hostab-web/app/views/kitchen/home/_list.html.erb
<% if @orders.any?  %>
  <% @orders.each  do |o| %>
      <section class="order-holder" data-time="<%= o.created_at.to_i %>">
        <h3>Pedido #<%= o.id %></h3>
        <article class="o-info">
          <p>Hóspede: <%= o.user.name%></p>
          <p>Local de entrega: <%= (o.delivery_location) ? o.delivery_location.name : "Não informado" %></p>
        </article>
        <article class="o-itens">
          <h4>Itens</h4>
          <ul>
            <% o.items.each do |i| %>
              <li>
                  <strong><%= i.food.title %> | Quantidade: <%= i.amount %> </strong>
                  <% unless i.observations.nil? %>
                    <p class="oi-observation">
                      obs: <%= i.observations %>
                    </p>
                  <% end %>
              </li>
            <% end %>
          </ul>
        </article>
        <article class="o-actions">
          <p><%= link_to 'Marcar como pronto', kitchen_kitchen_ready_path(o), method: :put, class: 'btn btn-primary' %></p>
          <p><%= link_to 'Remover pedido', kitchen_home_path(o), method: :delete, class: 'btn btn-danger', confirm: 'Deseja realmente excluir esse pedido?'  %></p>
        </article>
      </section>
  <% end %>
<% end %>

hostab-web/app/views/kitchen/home/index.html.erb
<% if @orders.empty? %>
  <strong>Nenhum pedido realizado até o momento</strong>
<% else %>
  <div id="all-orders">
    <input type="hidden" id="url-polling" value="<%= kitchen_polling_orders_path %>" />
    <%= render "list" %>
  </div>
<% end %>