hostab-web/config/routes.rb
# -*- encoding : utf-8 -*-
HostabWeb::Application.routes.draw do
  apipie

  namespace :api do
    namespace :v1 do
      resources :delivery_locations
    	scope "/users/:user_id" do
    		resources :orders, only: [:create, :update, :show, :index]
    	end

      scope "/orders/:order_id" do
        resources :order_items, only: [:create, :index, :destroy, :show, :update]
      end

      resources :auth, only: [:create]
      resources :food_types, only: [:index] do
        resources :foods, only: [:index, :show]
      end
    end
  end
  namespace :kitchen do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'
    get   '/polling_orders', to: 'home#polling_orders'
    put '/set_as_ready/:order_id', to: 'home#set_as_ready', as: 'kitchen_ready'

    resources :home, only: [:index, :destroy]
  end
  
  namespace :admin do
    get   '/sign_in',   to: 'sessions#new'
    post  '/sign_in',   to: 'sessions#create'
    get   '/sign_out',  to: 'sessions#destroy'

    resources :home, only: [:index]
    resources :delivery_locations
    resources :menus
    resources :food_types do
      resources :foods
    end

    scope 'food/:id/' do
      post '/image',    to: 'foods#add_image'
      delete '/image/:image_id',  to: 'foods#remove_image', as: 'remove_image'
    end

    resources :promotions, only: [:index]
    resources :room_services, only: [:index]
    resources :users, only: [:edit, :update]

    get '/guests/search', to: 'guests#search'
    resources :guests

    root to: "home#index"
  end
  

  root to: "apipie/apipies#index"
end

hostab-web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= current_user.company.name %> - Admin</title>
	  <meta charset="utf-8" />
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		 <div class="navbar navbar-fixed-top">
		   <div class="navbar-inner">
		     <div class="container">
		     	<%= link_to current_user.company.name, admin_home_index_path, :class => "brand"%>
		       <div class="nav-collapse collapse" id="main-menu">
		        <ul class="nav" id="main-menu-left">
		          <li class="<%= ((request.fullpath.include? 'food_type' or request.fullpath.include? 'menu') ? 'current' : '')%>"><%= link_to current_user.company.menu_configuration["cardapio"], admin_menus_path %></li>
		          <li><%= link_to current_user.company.menu_configuration["promocoes"], admin_promotions_path %></li>
		          <li><%= link_to current_user.company.menu_configuration["hospedes"], admin_guests_path %></li>
		          <li><%= link_to current_user.company.menu_configuration["room_service"], admin_room_services_path%></li>
		        </ul>
		        <ul class="nav pull-right">
		        	<li><%= link_to 'Configurações', admin_delivery_locations_path %></li>
		        	<li><%= link_to 'Sair', admin_sign_out_path%></li>
		        </ul>
		       </div>
		     </div>
		   </div>
		 </div>
		<div class="container" id="main-page">
			<%= yield %>
		</div>
	</body>
</html>

hostab-web/app/views/layouts/kitchen.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hostab - Painel da Cozinha</title>
    <meta charset="utf-8" />
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
     <div class="navbar navbar-fixed-top">
       <div class="navbar-inner">
         <div class="container">
          <%= link_to 'Hostab - Painel da cozinha', admin_home_index_path, :class => "brand"%>
           <div class="nav-collapse collapse" id="main-menu">
            <ul class="nav pull-right">
              <li><%= link_to 'Sair', kitchen_sign_out_path%></li>
            </ul>
           </div>
         </div>
       </div>
     </div>
    <div class="container" id="main-page">
      <%= yield %>
    </div>
  </body>
</html>